#ifndef BTSTACK_CONFIG_H
#define BTSTACK_CONFIG_H

// BTstack Configuration for Pico W - BLE ONLY

#define HAVE_EMBEDDED_TIME_MS
#define HAVE_MALLOC
#define HAVE_POSIX_FILE_IO
#define HAVE_BTSTACK_STDIN

#define HAVE_CYW43_ARCH

// Bluetooth Low Energy support
#define HAVE_BLE
#define ENABLE_ATT_SERVER
#define ENABLE_GATT_SERVER
#define ENABLE_SM
#define ENABLE_LE_PERIPHERAL

// Hardware configuration
#define HCI_ACL_PAYLOAD_SIZE (1691 + 4)
#define MAX_NR_GATT_CLIENT_VALUE_QUERIES 1
#define MAX_NR_HCI_CONNECTIONS 1
#define MAX_NR_L2CAP_CHANNELS  4
#define MAX_NR_L2CAP_SERVICES  4
#define MAX_NR_SM_LOOKUP_ENTRIES 3
#define MAX_NR_WHITELIST_ENTRIES 1
#define MAX_NR_LE_DEVICE_DB_ENTRIES 10
#define NVM_NUM_DEVICE_DB_ENTRIES 10

#define ENABLE_PRINTF_HEXDUMP

// CYW43 specific
#define HCI_OUTGOING_PRE_BUFFER_SIZE 4
#define HCI_ACL_CHUNK_SIZE_ALIGNMENT 4

#endif
